require('pry-byebug')
require_relative('models/customer.rb')
require_relative('models/movie.rb')
require_relative('models/ticket.rb')

customer1 = Customer.new({'name' => 'Jeff', 'funds' => '55'})
customer2 = Customer.new({'name' => 'Julie', 'funds' => '34'})
customer3 = Customer.new({'name' => 'John', 'funds' => '33'})
customer4 = Customer.new({'name' => 'Steve', 'funds' => '10'})
customer1.save()
customer2.save()
customer3.save()
customer4.save()

movie1 = Movie.new({'title' => 'The Big Lebowski', 'price' => '5'})
movie2 = Movie.new({'title' => 'The Vanishing', 'price' => '5'})
movie3 = Movie.new({'title' => 'Arlington Road', 'price' => '5'})
movie4 = Movie.new({'title' => 'Con Air', 'price' => '5'})
movie5 = Movie.new({'title' => 'Magnolia', 'price' => '5'})
movie6 = Movie.new({'title' => 'Fallen', 'price' => '5'})
movie1.save()
movie2.save()
movie3.save()
movie4.save()
movie5.save()
movie6.save()

ticket1 = Ticket.new({'customer_id' => customer1.id, 'movie_id' => movie1.id})
ticket2 = Ticket.new({'customer_id' => customer1.id, 'movie_id' => movie2.id})
ticket3 = Ticket.new({'customer_id' => customer1.id, 'movie_id' => movie3.id})
ticket4 = Ticket.new({'customer_id' => customer2.id, 'movie_id' => movie1.id})
ticket5 = Ticket.new({'customer_id' => customer2.id, 'movie_id' => movie5.id})
ticket6 = Ticket.new({'customer_id' => customer3.id, 'movie_id' => movie1.id})
ticket7 = Ticket.new({'customer_id' => customer3.id, 'movie_id' => movie6.id})
ticket8 = Ticket.new({'customer_id' => customer4.id, 'movie_id' => movie1.id})
ticket9 = Ticket.new({'customer_id' => customer4.id, 'movie_id' => movie4.id})
ticket1.save()
ticket2.save()
ticket3.save()
ticket4.save()
ticket5.save()
ticket6.save()
ticket7.save()
ticket8.save()
ticket9.save()

binding.pry
nil
